#!/usr/bin/env ruby
# frozen_string_literal: true

require "pathname"

ROOT = Pathname(__dir__).join("..").expand_path
DEFAULT_TAP_NAME = "shonenada/tap"

Package = Struct.new(:type, :id, :name, :description, :version, keyword_init: true)

def detect_tap_name
  origin_url = `git config --get remote.origin.url 2>/dev/null`.strip
  return DEFAULT_TAP_NAME if origin_url.empty?

  match = origin_url.match(%r{github\.com[:/](?<owner>[^/]+)/(?<repo>homebrew-[^/.]+?)(?:\.git)?$})
  return DEFAULT_TAP_NAME unless match

  "#{match[:owner]}/#{match[:repo].sub(/\Ahomebrew-/, "")}"
end

TAP_NAME = detect_tap_name

def parse_formula(path)
  content = path.read
  id = path.basename(".rb").to_s

  Package.new(
    type: :formula,
    id: id,
    name: id,
    description: content[/^\s*desc\s+"([^"]+)"/, 1] || "No description provided.",
    version: content[/^\s*version\s+"([^"]+)"/, 1] || "No version provided."
  )
end

def parse_cask(path)
  content = path.read
  id = path.basename(".rb").to_s

  Package.new(
    type: :cask,
    id: id,
    name: content[/^\s*name\s+"([^"]+)"/, 1] || id,
    description: content[/^\s*desc\s+"([^"]+)"/, 1] || "No description provided.",
    version: content[/^\s*version\s+"([^"]+)"/, 1] || "No version provided."
  )
end

def install_command(package)
  if package.type == :cask
    "brew install --cask #{TAP_NAME}/#{package.id}"
  else
    "brew install #{TAP_NAME}/#{package.id}"
  end
end

def render_section(title, packages)
  lines = ["## #{title}", ""]

  packages.each do |package|
    lines << "### #{package.name}"
    lines << ""
    lines << "- Name: `#{package.name}`"
    lines << "- Version: `#{package.version}`"
    lines << "- Description: #{package.description}"
    lines << "- Install: `#{install_command(package)}`"
    lines << ""
  end

  lines.join("\n").rstrip
end

formulae = ROOT.glob("Formula/*.rb").sort.map { |path| parse_formula(path) }
casks = ROOT.glob("Casks/*.rb").sort.map { |path| parse_cask(path) }

sections = []
sections << render_section("Formulae", formulae) unless formulae.empty?
sections << render_section("Casks", casks) unless casks.empty?

readme = <<~README
  # Homebrew Tap

  This README is generated by `scripts/update-readme.rb`. Run it after adding or updating formulae or casks.

  #{sections.join("\n\n")}
README

ROOT.join("README.md").write(readme)
